Squashed commit of the following:
commit b9ab747f383e26f90d18bd449640adec97c8dc3c
Author: Giovanni Bajo <rasky@develer.com>
Date:   Mon Feb 12 14:29:48 2024 +0100

    inthandler: preserve full 64-bit value of stack pointer in the context

commit 103de2bfc7a83f34c4451f3280e1235560f3c77b
Author: Giovanni Bajo <rasky@develer.com>
Date:   Mon Feb 12 14:29:31 2024 +0100

    inspector: incremental fixes and improvements to the disassembler

commit 16386ca55abf7922ec5eb3adf5b35e54db549d3e
Author: Giovanni Bajo <rasky@develer.com>
Date:   Mon Feb 12 14:29:12 2024 +0100

    exception: improve error reporting in case of invalid 64-bit address

commit 81c3c75516fbcc9cd3670874165567fb6172e804
Author: Giovanni Bajo <rasky@develer.com>
Date:   Mon Feb 12 09:35:27 2024 +0100

    wav64: add wav64_get_bitrate API

commit 0dc28e4246a31befbf567bfea8166146b4e2f62f
Author: Giovanni Bajo <rasky@develer.com>
Date:   Mon Feb 12 09:34:33 2024 +0100

    mksprite: add IHQ to the help page